export default {
    "ab":"Abkhaze",
    "af":"Afrikaans",
    "ak":"Akan",
    "sq":"Albanais",
    "am":"Amharique",
    "ar":"Arabe",
    "an":"Aragonais",
    "hy":"Arménien",
    "as":"Assamais",
    "av":"Avar",
    "ae":"Avestique",
    "ay":"Aymara",
    "az":"Azéri",
    "ba":"Bachkir",
    "bm":"Bambara",
    "eu":"Basque",
    "be":"Biélorusse",
    "bn":"Bengali",
    "bh":"Langues Biharis",
    "bi":"Bichlamar",
    "bo":"Tibétain",
    "bs":"Bosniaque",
    "br":"Breton",
    "bg":"Bulgare",
    "my":"Birman",
    "ca":"Catalan; Valencien",
    "cs":"Tchèque",
    "ch":"Chamorro",
    "ce":"Tchétchène",
    "zh":"Chinois",
    "cu":"Slavon D'Église; Vieux Slave; Slavon Liturgique; Vieux Bulgare",
    "cv":"Tchouvache",
    "kw":"Cornique",
    "co":"Corse",
    "cr":"Cree",
    "cy":"Gallois",
    "da":"Danois",
    "de":"Allemand",
    "dv":"Maldivien",
    "nl":"Néerlandais; Flamand",
    "dz":"Dzongkha",
    "el":"Grec Moderne (Après 1453)",
    "en":"Anglais",
    "eo":"Espéranto",
    "et":"Estonien",
    "ee":"Éwé",
    "fo":"Féroïen",
    "fa":"Persan",
    "fj":"Fidjien",
    "fi":"Finnois",
    "fr":"Français",
    "fy":"Frison Occidental",
    "ff":"Peul",
    "ka":"Géorgien",
    "gd":"Gaélique; Gaélique Écossais",
    "ga":"Irlandais",
    "gl":"Galicien",
    "gv":"Manx; Mannois",
    "gn":"Guarani",
    "gu":"Goudjrati",
    "ht":"Haïtien; Créole Haïtien",
    "ha":"Haoussa",
    "he":"Hébreu",
    "hz":"Herero",
    "hi":"Hindi",
    "ho":"Hiri Motu",
    "hr":"Croate",
    "hu":"Hongrois",
    "ig":"Igbo",
    "is":"Islandais",
    "io":"Ido",
    "ii":"Yi De Sichuan",
    "iu":"Inuktitut",
    "ie":"Interlingue",
    "ia":"Interlingua (Langue Auxiliaire Internationale)",
    "id":"Indonésien",
    "ik":"Inupiaq",
    "it":"Italien",
    "jv":"Javanais",
    "ja":"Japonais",
    "kl":"Groenlandais",
    "kn":"Kannada",
    "ks":"Kashmiri",
    "kr":"Kanouri",
    "kk":"Kazakh",
    "km":"Khmer Central",
    "ki":"Kikuyu",
    "rw":"Rwanda",
    "ky":"Kirghiz",
    "kv":"Kom",
    "kg":"Kongo",
    "ko":"Coréen",
    "kj":"Kuanyama; Kwanyama",
    "ku":"Kurde",
    "lo":"Lao",
    "la":"Latin",
    "lv":"Letton",
    "li":"Limbourgeois",
    "ln":"Lingala",
    "lt":"Lituanien",
    "lb":"Luxembourgeois",
    "lu":"Luba-Katanga",
    "lg":"Ganda",
    "mk":"Macédonien",
    "mh":"Marshall",
    "ml":"Malayalam",
    "mi":"Maori",
    "mr":"Marathe",
    "ms":"Malais",
    "mg":"Malgache",
    "mt":"Maltais",
    "mn":"Mongol",
    "na":"Nauruan",
    "nv":"Navaho",
    "nr":"Ndébélé Du Sud",
    "nd":"Ndébélé Du Nord",
    "ng":"Ndonga",
    "ne":"Népalais",
    "nn":"Norvégien Nynorsk; Nynorsk, Norvégien",
    "nb":"Norvégien Bokmål",
    "no":"Norvégien",
    "ny":"Chichewa; Chewa; Nyanja",
    "oc":"Occitan (Après 1500)",
    "oj":"Ojibwa",
    "or":"Oriya",
    "om":"Galla",
    "os":"Ossète",
    "pa":"Pendjabi",
    "pi":"Pali",
    "pl":"Polonais",
    "pt":"Portugais",
    "ps":"Pachto",
    "qu":"Quechua",
    "rm":"Romanche",
    "ro":"Roumain; Moldave",
    "rn":"Rundi",
    "ru":"Russe",
    "sg":"Sango",
    "sa":"Sanskrit",
    "si":"Singhalais",
    "sk":"Slovaque",
    "sl":"Slovène",
    "se":"Sami Du Nord",
    "sm":"Samoan",
    "sn":"Shona",
    "sd":"Sindhi",
    "so":"Somali",
    "st":"Sotho Du Sud",
    "es":"Espagnol; Castillan",
    "sc":"Sarde",
    "sr":"Serbe",
    "ss":"Swati",
    "su":"Soundanais",
    "sw":"Swahili",
    "sv":"Suédois",
    "ty":"Tahitien",
    "ta":"Tamoul",
    "tt":"Tatar",
    "te":"Télougou",
    "tg":"Tadjik",
    "tl":"Tagalog",
    "th":"Thaï",
    "ti":"Tigrigna",
    "to":"Tongan (Îles Tonga)",
    "tn":"Tswana",
    "ts":"Tsonga",
    "tk":"Turkmène",
    "tr":"Turc",
    "tw":"Twi",
    "ug":"Ouïgour",
    "uk":"Ukrainien",
    "ur":"Ourdou",
    "uz":"Ouszbek",
    "ve":"Venda",
    "vi":"Vietnamien",
    "vo":"Volapük",
    "wa":"Wallon",
    "wo":"Wolof",
    "xh":"Xhosa",
    "yi":"Yiddish",
    "yo":"Yoruba",
    "za":"Zhuang; Chuang",
    "zu":"Zoulou"
};